# yaml-language-server: $schema=https://cubic3d.github.io/crd-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: project-zomboid
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - secretKey: SERVER_NAME
      remoteRef:
        key: project-zomboid
        property: server_name

    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: project-zomboid
        property: admin_password

    - secretKey: RCON_PASSWORD
      remoteRef:
        key: project-zomboid
        property: rcon_password
