apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-zomboid-runtime
  labels:
    app.kubernetes.io/name: project-zomboid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath
