# yaml-language-server: $schema=https://cubic3d.github.io/crd-catalog/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: nas
spec:
  backend:
    s3:
      endpoint: nas.${domain}:3000
      bucket: kopiur
      auth:
        secretRef:
          name: kopiur-nas

  encryption:
    passwordSecretRef:
      name: kopiur-nas
      namespace: system
      key: KOPIA_PASSWORD

  server:
    namespace: system
    auth:
      secretRef:
        name: kopiur-nas
        usernameKey: UI_USERNAME
        passwordKey: UI_PASSWORD

  allowedNamespaces:
    all: true

  credentialProjection:
    allowed: true

  identityDefaults:
    hostnameExpr: namespace
    usernameExpr: policyName

  scheduleDefaults:
    timezone: Europe/Berlin

  moverDefaults:
    ttlSecondsAfterFinished: 300
