[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = 1
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
FLATE_PATH = "{{config_root}}/kubernetes/flux/cluster"

[tools]
ansible = "latest"
flux2 = "latest"
helmfile = "latest"
kubectl = "latest"
sops = "latest"
talosctl = "latest"
task = "latest"
uv = "latest"
yq = "latest"
k9s = "latest"
just = "latest"
"github:mitsuhiko/minijinja" = "latest"
gum = "latest"
kustomize = "latest"
helm = "latest"
"github:home-operations/flate" = "latest"
# 1password is provided by the system
