# yaml-language-server: $schema=https://cubic3d.github.io/crd-catalog/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: authelia-service
spec:
  from:
    - &policy
      group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: automation
    - <<: *policy
      namespace: hosted
    - <<: *policy
      namespace: kube-system
    - <<: *policy
      namespace: longhorn-system
    - <<: *policy
      namespace: media
    - <<: *policy
      namespace: nx
    - <<: *policy
      namespace: network
    - <<: *policy
      namespace: system

  to:
    - group: ""
      kind: Service
      name: authelia
