# yaml-language-server: $schema=https://cubic3d.github.io/crd-catalog/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: shelfmark
spec:
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
  ref:
    tag: 5.0.0
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
