# yaml-language-server: $schema=https://cubic3d.github.io/crd-catalog/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: depName=siderolabs/talos datasource=custom.talos-factory
    version: v1.13.5

  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: |-
        status.phase != 'Running'

    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Restore
      expr: |-
        !(status.phase in ['Resolving', 'Restoring'])
