# yaml-language-server: $schema=https://cubic3d.github.io/crd-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        SMTP_HOST: "{{ .m_smtp_server }}"
        SMTP_PORT: "{{ .m_port }}"
        SMTP_USER: "{{ .m_username }}"
        SMTP_PASSWORD: "{{ .m_password }}"
        OIDC_CLIENT_SECRET: "{{ .a_oidc_secret_mealie_plain }}"
        OPENAI_API_KEY: "{{ .o_api_key_mealie }}"

  dataFrom:
    - extract:
        key: mailing
      rewrite:
        - regexp:
            source: (.*)
            target: m_$1

    - extract:
        key: authelia
      rewrite:
        - regexp:
            source: (.*)
            target: a_$1

    - extract:
        key: openrouter
      rewrite:
        - regexp:
            source: (.*)
            target: o_$1
