# yaml-language-server: $schema=https://cubic3d.github.io/crd-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: govee2mqtt
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        # FIXME: https://github.com/wez/govee2mqtt/issues/682
        # GOVEE_EMAIL: "{{ .govee_email }}"
        # GOVEE_PASSWORD: "{{ .govee_password }}"
        GOVEE_API_KEY: "{{ .govee_api_key }}"

  dataFrom:
    - extract:
        key: govee
      rewrite:
        - regexp:
            source: (.*)
            target: govee_$1
