# yaml-language-server: $schema=https://cubic3d.github.io/crd-catalog/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${app}
  annotations:
    kopiur.home-operations.com/allow-identity-change: "true"
spec:
  mover:
    cache:
      capacity: ${kopiur_capacity:=1Gi}
      mode: Ephemeral
      storageClassName: openebs-hostpath
    securityContext:
      runAsUser: ${kopiur_mover_uid:=2000}
      runAsGroup: ${kopiur_mover_gid:=2000}
  staging:
    storageClassName: ${kopiur_storageclass:=longhorn-tmp}
  repository:
    kind: ClusterRepository
    name: nas
  retention:
    keepHourly: 24
    keepDaily: 7
    keepWeekly: 4
  compression:
    compressor: zstd-fastest
  sources:
    - pvc:
        name: "${kopiur_claim:-${app}}"
  verification:
    deep:
      schedule:
        cron: H 5 1 * *
    quick:
      schedule:
        cron: H 3 * * *
  volumeSnapshotClassName: ${kopiur_snapshotclass:=longhorn}
  credentialProjection:
    enabled: true
